[phases.setup]
nixPkgs = ["nodejs_20", "npm_9"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -s -l $PORT"

[variables]
NODE_ENV = "production"